agentname: master
giturl:
 path: https://github.com/dhivyakiran/portal.git
nexus:
 type: zip
 credentialsId: b540a6d8-00dc-4524-af49-8d99d20d3919
 groupId: sp.sd
 nexusUrl: localhost:8081
 nexusVersion: 3.2
 repository: helloworld-angularapp
sonarqube:
 url: 
dev_s3bucket:
 salesurl:
 agenturl:
 membersurl:
