agentname: 'slave1'
giturl:
 cmsservice: https://github.com/dhivyakiran/nodejs1.git
 eisservice: https://github.com/dhivyakiran/nodejs1.git
branch: development
test: true
sonar: true
checkmarx: true
ecrregistry:
 nonprod: '450343572378'
 prod: '450343572378' 
ecrrepo:
 nonprod: 450343572378.dkr.ecr.us-east-1.amazonaws.com/salesportal-repo
 prod: 450343572378.dkr.ecr.us-east-1.amazonaws.com/salesportal-repo
