agentname: master
giturl:
 cmsservice: https://github.com/dhivyakiran/nodejs1.git
 eisservice: https://github.com/dhivyakiran/nodejs1.git
branch: development
test: true
sonar: true
checkmarx: true
ecrname: salesportal




